environments:
  dev:
    auth-url: https://tms-agri-dev.daedong.co.kr/api/auth
    api-url: https://tms-agri-dev.daedong.co.kr/api/tms
    credentials:
      userId: "mjha"
      password: "123qwer@"

test-config:
  timeout: 30000
  retry-count: 3
  concurrent-requests: 5
